fetch mirror group status
ceph/go-ceph pull request #1009
Opened 2024-07-07 12:16 UTC by sp98

## Checklist
- [ ] Added tests for features and functional changes
- [ ] Public functions and types are documented
- [ ] Standard formatting is applied to Go code
- [ ] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [ ] Ran `make api-update` to record new APIs

New or infrequent contributors may want to review the go-ceph [Developer's Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) including the section on how we track [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) and the [API Stability Plan](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md).

The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is out of date with the base branch.

2024-07-07 15:17 UTC, phlogistonjohn requested changes
The tests are rather cranky. I've tried to point out a few reasons why.

The big item you need to tackle first is to avoid adding new code to an existing file. Start a new file for the new api and the related types, maybe something like `mirror_group_status.go` ?

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +		C.uint32_t(0))
https://github.com/ceph/ceph/blob/reef/src/include/rbd/librbd.h#L1436

I don't understand these changes to `rbd_group_image_add`. It only has the four arguments that we're already passing.

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +		C.uint32_t(0))
Same. Where are these extra args coming from?

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +// MirrorImageState represents the mirroring state of a RBD image.
Typo/copy-paste mistake is confusing the linter.

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +	// MirrorGrouptatusStateUnknown is equivalent to MIRROR_GROUP_STATUS_STATE_UNKNOWN
Typo is confusing the linter.

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +	MirrorGroupStatusStateStopped = MirrorGroupStatusState(C.MIRROR_GROUP_STATUS_STATE_STOPPED)
Most, if not all (I didn't check), of these flags are unknown on older versions of the code. These should be moved to a new file.

2024-07-07 15:17 UTC, phlogistonjohn commented on rbd/group.go
> +func GetGlobalMirrorGroupStatus(ioctx *rados.IOContext, groupName string) (GlobalMirrorGroupStatus, error) {
New APIs like this need to be added to a new file and then have build tags applied to them to (a) control what versions of ceph it'll build with and (b) be initially marked as preview as per [our docs](https://github.com/ceph/go-ceph/blob/master/docs/development.md#documentation-conventions) and the [policy](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md).

2024-07-09 12:10 UTC, sp98 commented
closing this in favor of https://github.com/ceph/go-ceph/pull/1010

2024-07-09 12:10 UTC, closed without merging