rbd: add EncryptionLoad api to support the rbd_encryption_load librbd…
ceph/go-ceph pull request #542
Opened 2021-07-27 09:13 UTC by effi-ofer

rbd: add EncryptionLoad api to support the rbd_encryption_load librbd api.

EncryptionLoad loads the encryption format information for an image and enables encrypted IO.  This is a new feature in Ceph Pacific.

Signed-off-by: Effi Ofer <effio@il.ibm.com>

## Checklist
- [x] Added tests for features and functional changes
- [x] Public functions and types are documented
- [x] Standard formatting is applied to Go code

2021-07-27 17:07 UTC, phlogistonjohn requested changes
One more small nitpick about the tests: you write the data with encryption enabled, and read it back from the same open image. I think it would be better for verification to close the image after writing and then reopen it with encryption enabled. That way we're unlikely to be hitting any caches, etc.

If you don't think this is a good idea, please let me know. Otherwise things are looking good!

2021-07-27 17:49 UTC, effi-ofer commented
> One more small nitpick about the tests: you write the data with encryption enabled, and read it back from the same open image. I think it would be better for verification to close the image after writing and then reopen it with encryption enabled. That way we're unlikely to be hitting any caches, etc.
> 
> If you don't think this is a good idea, please let me know. Otherwise things are looking good!

Done

2021-07-29 13:10 UTC, phlogistonjohn submitted a review, later dismissed
LGTM. Thanks a bunch!

2021-08-01 06:58 UTC, effi-ofer commented
@phlogistonjohn thanks for the review.  Any idea why the test-suite is failing?

2021-08-01 11:39 UTC, phlogistonjohn commented
> @phlogistonjohn thanks for the review. Any idea why the test-suite is failing?

Unfortunately, no. It seems like it could be a time out. It certainly was the first time, but the most recent time as of this writing is more mysterious. I've started the CI again. If if fails again in a similar way I'll investigate deeper, but I'm hoping we're just getting unlucky with test flakes.

2021-08-01 13:49 UTC, phlogistonjohn commented
Good news: it looks like we did just get unlucky with the previous two runs, the CI has passed now.

2021-08-02 06:47 UTC, effi-ofer commented
> Good news: it looks like we did just get unlucky with the previous two runs, the CI has passed now.

That's awesome and thank you @phlogistonjohn.  What do we need to do next to get this merged?

2021-08-02 14:02 UTC, phlogistonjohn commented
> > Good news: it looks like we did just get unlucky with the previous two runs, the CI has passed now.
> 
> That's awesome and thank you @phlogistonjohn. What do we need to do next to get this merged?

A second approving review. Please be patient, as most of our maintainers do go-ceph work as part of their jobs and I know some people are unavailable today.

2021-08-02 14:24 UTC, effi-ofer commented
> > > Good news: it looks like we did just get unlucky with the previous two runs, the CI has passed now.
> > 
> > 
> > That's awesome and thank you @phlogistonjohn. What do we need to do next to get this merged?
> 
> A second approving review. Please be patient, as most of our maintainers do go-ceph work as part of their jobs and I know some people are unavailable today.

No rush.  And thanks for responding so quickly.

2021-08-02 14:43 UTC, nixpanic approved these changes
@mergifyio rebase

(There is no need to rebase manually on top of the master branch. When using GitHub, this adds a merge-commit which we usually do not like. When your PR goes out-of-sync with the master branch, mergify will automatically resolve it for you if there are no conflicts.)

2021-08-02 18:49 UTC, phlogistonjohn approved these changes
Re-approving.

2021-08-02 18:49 UTC, phlogistonjohn commented
@mergifyio rebase

2021-08-02 21:03 UTC, merged