docs: add a API stability document
ceph/go-ceph pull request #552
Opened 2021-08-10 15:11 UTC by ansiwen

Lets work out an API stability document with this PR.

Signed-off-by: Sven Anderson <sven@redhat.com>

2021-08-10 17:51 UTC, phlogistonjohn reviewed
Awesome start. I'll do a 2nd more thoughtful pass soon but this looks like a really solid foundation to me. One minor typo/spelling mistake highlighted below.

2021-08-10 17:51 UTC, phlogistonjohn commented on docs/api-stability.md
> +changes in future releases reagarding preview APIs. Usually new exported APIs
Spelling: `regarding`

2021-08-16 14:23 UTC, phlogistonjohn requested changes
I have one content change suggested. We don't need to take my exact wording but I do think we need to say something along these lines or it's too easy to forget to stabilize apis.

2021-08-16 14:23 UTC, phlogistonjohn commented on docs/api-stability.md
> +are introduced with this level first and become stable with a later release.
Let's be a tad bit more specific wrt the stabilization schedule. Something like:
> Usually new exported APIs are introduced with this level first and become stable within two future releases unless a major change to the API is required which then "resets" the counter. The schedule for preview APIs becoming stable is tracked in a separate document (link TDB).

2021-08-23 16:24 UTC, phlogistonjohn submitted a review, later dismissed
Newest revision looks good. I am approving to show my approval of the content, but do please squash the changes prior to removing the label, thanks!

2021-08-25 13:47 UTC, ansiwen commented
> do please squash the changes prior to removing the label, thanks!

Sure, that's what I set the label for. 😉

2021-08-25 16:50 UTC, phlogistonjohn approved these changes
LGTM, thanks!

2021-08-25 16:51 UTC, merged