Rgw/admin: add num_shards to  bucket struct field
ceph/go-ceph pull request #704
Opened 2022-06-10 14:37 UTC by oneto1

This change add a new bucket struct field , so we can use rgw.admin.API.GetBucketInfo() to get a bucket's num_shards.

```
radosgw-admin bucket stats --bucket test
{
    "bucket": "test",
    "num_shards": 11,    <<<<    SharksNum *uint64 `json:"num_shards"
    "tenant": "",
    "zonegroup": "d9d22c42-ea25-44df-bded-506b5d64bc82",
    ... 
}
```

## Checklist
- [ ] Added tests for features and functional changes
- [ ] Public functions and types are documented
- [x] Standard formatting is applied to Go code
- [ ] Is this a new API? Added a new file that begins with `//go:build ceph_preview`

2022-06-30 11:58 UTC, leseb reviewed
Please have commit message body similar to what's written in the PR's description, thanks!

2022-06-30 12:06 UTC, oneto1 commented
> Please have commit message body similar to what's written in the PR's description, thanks!

done

2022-06-30 12:18 UTC, thotz submitted a review, later dismissed

2022-06-30 12:48 UTC, leseb approved these changes

2022-06-30 13:11 UTC, oneto1 commented
Format code to pass CI.

2022-06-30 13:18 UTC, leseb requested changes
Please squash

2022-06-30 13:29 UTC, oneto1 commented
My mistake, sorry

2022-07-01 07:20 UTC, leseb approved these changes

2022-07-05 14:24 UTC, phlogistonjohn commented
Changes look reasonable to me. I'll give @thotz a couple of days to re-approve but if he's unavailable/too busy to re approve I'll try to do so by the end of the week.

2022-07-18 13:24 UTC, thotz approved these changes

2022-07-18 13:40 UTC, merged