entrypoint: Remove token file after use
ceph/go-ceph pull request #733
Opened 2022-07-08 11:58 UTC by anoopcs9

File named `token` was a left over from mirroring setup done via entrypoint.sh

2022-07-08 14:55 UTC, phlogistonjohn requested changes
I'm a little unclear on what the change is accomplishing?  Is it just a cleanliness thing?
One advantage of leaving the token behind is that it can be reused later by a human doing debugging / special stuff.
Maybe printing the content of token would be a better way to accomplish that an be cleaner?

2022-07-08 15:42 UTC, anoopcs9 commented on entrypoint.sh
> +    echo "enabled" > "${MIRROR_STATE}" && rm -f token
I understand. This will be changed.

2022-07-08 15:42 UTC, anoopcs9 commented
> I'm a little unclear on what the change is accomplishing? Is it just a cleanliness thing?

Yeah, `token` file existed after the execution of _test-containers-test_ target.

> One advantage of leaving the token behind is that it can be reused later by a human doing debugging / special stuff. Maybe printing the content of token would be a better way to accomplish that and be cleaner?

Sure, we'll use the other way to provide token via standard input as mentioned in [docs](https://docs.ceph.com/en/quincy/rbd/rbd-mirroring/?#bootstrap-peers).

2022-07-10 15:05 UTC, phlogistonjohn approved these changes

2022-07-10 15:06 UTC, merged