feat(cephfs): implementation of mkdirs
ceph/go-ceph pull request #832
Opened 2023-02-12 23:15 UTC by maitredede

Hello, this PR adds "ceph_mkdirs" implementation (to create path+subpath at once).

## Checklist
- [ ] Added tests for features and functional changes
- [ ] Public functions and types are documented
- [ ] Standard formatting is applied to Go code
- [ ] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [ ] Ran `make api-update` to record new APIs

New or infrequent contributors may want to review the go-ceph [Developer's Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) including the section on how we track [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) and the [API Stability Plan](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md).

The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is out of date with the base branch.

2023-02-13 05:50 UTC, anoopcs9 commented
> ## Checklist
> 
>     * [ ]  Added tests for features and functional changes
> 
>     * [ ]  Public functions and types are documented
> 
>     * [ ]  Standard formatting is applied to Go code
> 
>     * [ ]  Is this a new API? Added a new file that begins with `//go:build ceph_preview`
> 
>     * [ ]  Ran `make api-update` to record new APIs
> 
> 
> New or infrequent contributors may want to review the go-ceph [Developer's Guide](https://github.com/ceph/go-ceph/blob/master/docs/development.md) including the section on how we track [API Status](https://github.com/ceph/go-ceph/blob/master/docs/development.md#api-status) and the [API Stability Plan](https://github.com/ceph/go-ceph/blob/master/docs/api-stability.md).
> 
> The go-ceph project uses mergify. View the [mergify command guide](https://docs.mergify.com/commands/#commands) for information on how to interact with mergify. Add a comment with `@Mergifyio` `rebase` to rebase your PR when github indicates that the PR is out of date with the base branch.

@maitredede Please go through the above checklist and make sure that every requirement is met.

2023-02-13 05:54 UTC, anoopcs9 commented
I see some unrelated changes in the pull request. Please make sure that you only touch the relevant API sections.

2023-02-13 09:29 UTC, maitredede commented
Hi @anoopcs9 , thanks for your time :smile: 

I have gone through all checks, but I don't know if I did well with `make api-update` (it raised an error, I tried to fix).

I have also used `make test-docker`. Is there something I have missed ?

2023-02-14 04:11 UTC, maitredede commented
Hello @phlogistonjohn,

Thanks for your reply. I have followed your instructions and updated my first post accordingly.

2023-02-14 06:06 UTC, anoopcs9 commented
> Without speaking for @anoopcs9 I think he might have meant to make use of the checkbox feature on github and tick off the boxes so that we know you followed each guideline.

Thank you John, that's exactly what I wanted.

@maitredede Thanks for making the required changes. Can you also avoid using the _preview_ suffix from the source file name? _makedirs_ itself holds good. Preview nature of the API is already indicated using the build tags inside which will get removed once it reaches the expected stable version in future.

2023-02-15 09:33 UTC, anoopcs9 reviewed
All good.

See below for 2 minor comments.

2023-02-15 09:33 UTC, anoopcs9 commented on cephfs/makedirs.go
> +//
Unnecessary empty new line?

2023-02-15 09:33 UTC, anoopcs9 commented on cephfs/makedirs_test.go
> +	assert.NoError(t, err)
It's just a matter of personal choice and I don't insist. But how about including the `dir.Close()` inside `assert.NoError` as below:
```
assert.NoError(t, dir.Close())
```

2023-02-16 06:23 UTC, anoopcs9 commented
@maitredede Can you also add `Signed-off-by:` in the commit message? Forgot to comment earlier.

2023-02-16 14:08 UTC, phlogistonjohn requested changes
Please fix the extra whitespace in the doc comment and add a signed off by line as @anoopcs9 suggested. After that I think we'll be good.

2023-02-19 21:28 UTC, maitredede commented
> Please fix the extra whitespace in the doc comment and add a signed off by line as @anoopcs9 suggested. After that I think we'll be good.

Hello :) The whitespace seams to be added by a code formatting tool (I don't know if it is the gofmt used by vscode extension), I will try to double check for my next PRs. The "signed off by" line has been added to my first message. Is is ok ?

2023-02-19 23:19 UTC, phlogistonjohn commented
> > Please fix the extra whitespace in the doc comment and add a signed off by line as @anoopcs9 suggested. After that I think we'll be good.
> 
> Hello :) The whitespace seams to be added by a code formatting tool (I don't know if it is the gofmt used by vscode extension), I will try to double check for my next PRs. The "signed off by" line has been added to my first message. Is is ok ?

It looks like you pasted it in the PR description. It belongs in the commit message. Try running `git commit --am -s`  it should update the commit message to contain the Signed-off-by line based on your local git user settings.

2023-02-19 23:27 UTC, maitredede commented
> It looks like you pasted it in the PR description. It belongs in the commit message. Try running `git commit --am -s` it should update the commit message to contain the Signed-off-by line based on your local git user settings.

Thanks for you help :)

2023-02-19 23:52 UTC, phlogistonjohn approved these changes
LGTM. Thank you for working with us to get everything meeting the process!

2023-02-20 05:59 UTC, anoopcs9 approved these changes
Thank you.

2023-02-20 06:00 UTC, merged