cephfs: Add futimes cephfs API
ceph/go-ceph pull request #875
Opened 2023-04-25 11:34 UTC by Nikhil-Ladha

Added a new cephfs API named `ceph_futimes`

Fixes: #254

Signed-off-by: Nikhil-Ladha <nikhilladha1999@gmail.com>

## Checklist
- [X] Added tests for features and functional changes
- [X] Public functions and types are documented
- [X] Standard formatting is applied to Go code
- [X] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [X] Ran `make api-update` to record new APIs

2023-05-03 13:42 UTC, phlogistonjohn requested changes

2023-05-03 13:42 UTC, phlogistonjohn commented on cephfs/file_ops.go
> +func (mount *MountInfo) Futimes(fd int, times [2]Timeval) error {
Similar comment to my feedback on #874 - since other APIs use a slice instead of a 2-element array I think we should stick to that consistently.

2023-05-09 09:01 UTC, Nikhil-Ladha commented
@Mergifyio rebase

2023-05-09 09:02 UTC, Nikhil-Ladha commented
@Mergifyio rebase

2023-05-15 10:15 UTC, Nikhil-Ladha commented
Awaiting review @phlogistonjohn and @anoopcs9 😅

2023-05-18 06:40 UTC, anoopcs9 approved these changes

2023-05-18 07:18 UTC, merged