rbd: include details for parent image in the trash
ceph/go-ceph pull request #906
Opened 2023-07-31 15:14 UTC by nixpanic

When a parent image has been removed, it will linger in the trash until all siblings are gone. The image is not accessible through it's name anymore, only through its ID.

The ImageSpec that is returned by Image.GetParent() now contains the Trash boolean and the ImageID to identify if the image is in the trash, and use OpenImageById() to access the removed parent image.

Related-to: ceph/ceph-csi#4013

## Checklist
- [x] Added tests for features and functional changes
- [ ] Public functions and types are documented
- [x] Standard formatting is applied to Go code
- [ ] Is this a new API? Added a new file that begins with `//go:build ceph_preview`
- [ ] Ran `make api-update` to record new APIs

2023-07-31 17:10 UTC, phlogistonjohn commented
Marked as an API change for review purposes. Change itself extends an existing type with new fields.

2023-07-31 17:17 UTC, phlogistonjohn commented
Change generally looks good to me and I'm willing to approve as-is, but first I want to ask. Would you mind completing the object and putting all fields present in rbd_linked_image_spec_t into the Go equivalent?

As of nautilus the fields are:
```C
typedef struct {
  int64_t pool_id;
  char *pool_name;
  char *pool_namespace;
  char *image_id;
  char *image_name;
  bool trash;
} rbd_linked_image_spec_t;

```

After your change we still lack `pool_id` and `pool_namespace`. I think it would be nice to proactively complete the set so that the next person who needs one of those doesn't need to file a PR :-)

What do you think?

2023-07-31 17:19 UTC, phlogistonjohn commented
Also, we can ignore failures in the CI against ceph main. This is due to a general infra issues on the ceph side related to nfs-ganesha builds.

2023-08-01 04:59 UTC, Rakshith-R requested changes
Thanks ! 
It looks good to me, 
added a small suggestion to check for ImageID too.

2023-08-01 04:59 UTC, Rakshith-R commented on rbd/rbd_nautilus_test.go
> +		assert.Equal(t, parentInfo.Image.ImageName, trashName)
```suggestion
		assert.Equal(t, parentInfo.Image.ImageName, trashName)
		assert.Equal(t, parentInfo.Image.ImageID, imgTrash.ImageID) 
```

Let's check ImageID too just to make sure we're fetching and converting the paramter from C successfully.

2023-08-01 09:41 UTC, Rakshith-R approved these changes
Lgtm !

2023-08-01 11:35 UTC, phlogistonjohn approved these changes
LGTM, thanks!

2023-08-02 06:02 UTC, anoopcs9 requested changes
Should we add an additional check to ensure that parent is no longer accessible by name but via ID(using `OpenImageById()`) as mentioned in the commit message?

2023-08-02 07:54 UTC, nixpanic commented on rbd/rbd_nautilus_test.go
> +		assert.NoError(t, err)
ok, done!

2023-08-02 07:55 UTC, nixpanic commented on rbd/rbd_nautilus_test.go
> +		assert.NoError(t, err)
ok, done!

2023-08-02 07:57 UTC, nixpanic commented
> Should we add an additional check to ensure that parent is no longer accessible by name but via ID(using `OpenImageById()`) as mentioned in the commit message?

That was taken from the discussion in ceph/ceph-csi#4013. I do not think we need to validate this particular RBD behavior. Possibly it could be added to a test that verifies the `Trash()` function.

2023-08-02 08:53 UTC, anoopcs9 approved these changes
lgtm.

2023-08-02 13:55 UTC, phlogistonjohn approved these changes
LGTM

2023-08-02 13:56 UTC, merged